baseURL = "https://AVAniketh0905.github.io/"
languageCode = "en-us"
title = "NiveshAI"
theme = "hugo-profile"

[params]
title = "NiveshAI"
subtitle = "We Do Business Things"
description = "A brief description of your business"
email = "niveshaitechnologies@gmail.com"
toc = false
socialShare = false
copyright = "Niveshai Tech"

[params.hero]
enable = true
title = "Welcome to NiveshAI"
subtitle = "Intelligent Solutions for Impactful Results"
content = "NiveshAI builds scalable, ML-powered forecasting tools that help QSR chains plan better, reduce waste, and improve operational efficiency."

[params.hero.button]
enable = false

[params.navbar]
disableSearch = true

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1

[[menu.main]]
identifier = "about"
name = "About"
url = "/about"
weight = 2

[[menu.main]]
identifier = "products"
name = "Products"
url = "/products/"
weight = 3

[[menu.main]]
identifier = "team"
name = "Team"
url = "/team/"
weight = 4

